- hosts: webservers
  become: yes
  tasks:
    - name: Include InstallJava tasks
      import_tasks: Install_Java_i.yml

    - name: Include webservers tasks
      import_tasks: Install_Webservers_i.yml
  handlers:
    - name: Restart and enable apache2
      service:
        name: apache2
        state: restarted
        enabled: yes
      listen: apache2 service

- hosts: controlnode
  become: yes
  tasks:
    - name: Include InstallJava tasks
      import_tasks: Install_Java_i.yml

    - name: Include InstallJenkins tasks
      import_tasks: Install_Jenkins_i.yml      